site_name: Folder Synchronizer
nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api_reference.md

theme:
  name: material

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
