name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install --no-root
        poetry install --only=dev
        poetry install -E simple
        poetry install -E server

    - name: Run linting
      run: |
        poetry run ruff check src --fix

    - name: Run type checks
      run: |
        poetry run mypy src

    - name: Run tests
      run: |
        poetry run pytest --cov=src tests

    - name: Build documentation
      run: |
        poetry run mkdocs build

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: site
